sudo: required

services:
- docker

before_install:
- docker pull node:9

script:
- docker run -t --rm -v ${PWD}:/deploy-ui -w /deploy-ui node:9 bash -c "npm install && npm run build"
- docker build -t glongzh/deploy-ui:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push glongzh/deploy-ui:$TRAVIS_BRANCH
